create table EMP(
	EMPNO VARCHAR,
	DEPTNO VARCHAR,
	DNAME VARCHAR,
	DESIG VARCHAR,
	BASIC NUMERIC,
	JOIN_DATE DATE,
	GENDER CHAR
	

);

ALTER TABLE EMP 
ADD PRIMARY KEY (EMPNO,DEPTNO);

INSERT INTO EMP VALUES
('E1', 'D1','JOHN' ,'MANAGER', 5001, '2015-04-09','M'),
('E2', 'D2','JENNY' ,'ASSOCIATE', 3001, '2013-06-12','F'),
('E3', 'D3','FINN' ,'NAME PARTNER', 10000, '2011-02-05','M');

SELECT * FROM EMP;

SELECT EMPNO, DNAME, DESIG, BASIC
FROM EMP;

SELECT EMPNO, DNAME
FROM EMP
WHERE DEPTNO='D1';

SELECT EMPNO,DEPTNO, DNAME, DESIG, BASIC
FROM EMP
ORDER BY BASIC DESC;

SELECT DISTINCT DESIG
FROM EMP;

SELECT EMPNO, DNAME, DESIG, BASIC
FROM EMP
ORDER BY BASIC DESC, DNAME;

SELECT *
FROM EMP
ORDER BY BASIC;

DELETE FROM EMP
WHERE BASIC< 5000;


