/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_cal_in (XDR *xdrs, cal_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arg1, 5,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cal_out (XDR *xdrs, cal_out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}
