/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct cal_in {
	char arg1[5];
	long arg2;
	long arg3;
};
typedef struct cal_in cal_in;

typedef long cal_out;

#define CAL_PROG 0x3544000
#define CAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CAL_PROC 1
extern  cal_out * cal_proc_1(cal_in *, CLIENT *);
extern  cal_out * cal_proc_1_svc(cal_in *, struct svc_req *);
extern int cal_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CAL_PROC 1
extern  cal_out * cal_proc_1();
extern  cal_out * cal_proc_1_svc();
extern int cal_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cal_in (XDR *, cal_in*);
extern  bool_t xdr_cal_out (XDR *, cal_out*);

#else /* K&R C */
extern bool_t xdr_cal_in ();
extern bool_t xdr_cal_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
